name: tradetrends
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5 # For API calls
  provider: ^6.0.5 # For state management
  web_socket_channel: ^2.4.0 # For real-time updates
  hive: ^2.2.3 # For local storage (offline mode)
  hive_flutter: ^1.1.0
  firebase_core: ^2.15.0 # Firebase integration
  firebase_messaging: ^14.6.5 # Push notifications
  intl: ^0.18.0 # Date formatting
  fl_chart: ^0.62.0 # For stock charts
  shared_preferences: ^2.2.0 # Store user preferences
  dio: ^5.2.1 # Alternative HTTP client (faster)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
