// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUU-nZOb6jP1KgDAodB3c_PK7VLmFFdcc',
    appId: '1:990950180616:web:57704176d61ee192a78ebd',
    messagingSenderId: '990950180616',
    projectId: 'tradetrends-89a9d',
    authDomain: 'tradetrends-89a9d.firebaseapp.com',
    storageBucket: 'tradetrends-89a9d.firebasestorage.app',
    measurementId: 'G-0MHX1ECCKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_P00ix7o_m1wq1-mr3VdGovo6b6i4yY',
    appId: '1:990950180616:android:5d57e6a5f80af059a78ebd',
    messagingSenderId: '990950180616',
    projectId: 'tradetrends-89a9d',
    storageBucket: 'tradetrends-89a9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwAXcbNYI964ltb0L2ivqp4QDXLFGTt74',
    appId: '1:990950180616:ios:1cc74d74fad0a7ada78ebd',
    messagingSenderId: '990950180616',
    projectId: 'tradetrends-89a9d',
    storageBucket: 'tradetrends-89a9d.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
